[package]
name = "collatz"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Helper functions related to the Collatz conjecture"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rayon = "1.5.1"